### ISSUE TITLE
Missing pre-processor directive "defined" cause warning.

### ISSUE THREAD

**Issue by 42Bastian** [STMicroelectronics/stm32h5xx-hal-driver#3]
Commit: b21b55fe8b05245d06c559a09a77edf5a0679a74
File: stm32h5xx_hal_def.h
Line: 178

https://github.com/STMicroelectronics/stm32h5xx_hal_driver/blob/b21b55fe8b05245d06c559a09a77edf5a0679a74/Inc/stm32h5xx_hal_def.h#L178

=>

`#if defined ( __CC_ARM   ) || (defined (__ARMCC_VERSION) && (__ARMCC_VERSION >= ARMCC_MIN_VERSION))`

**Comment by TOUNSTM** [comment]
Hello @42Bastian,

Thank you for your contribution. Could you please confirm if the issue occurs solely when the `-Wundef` flag is activated? 

With regards,

**Comment by 42Bastian** [comment]
Only with -Wall (whicht includes -Wundef).

**Comment by TOUNSTM** [comment]
See also https://github.com/STMicroelectronics/STM32CubeU5/issues/16

**Comment by 42Bastian** [comment]
Wow, I forgot about this. And in two years no fix?! :(

**Comment by TOUNSTM** [comment]
ST Internal Reference: 181063

**Comment by ra1nb0w** [comment]
obviously, same issue for STM32CubeH5

**Comment by ALABSTM** [comment]
> obviously, same issue for STM32CubeH5

Hi @ra1nb0w,

The STM32CubeH5 repository points to this one using the "submodule" technique. Once the link updated, the fix will propagate to that repository too.

With regards,
